= Apache TomEE and custom Resources

In this sample we're going to explore how to create a custom resource in +Apache TomEE+ for +MongoDB+ so we can use
+@Resource+ annotation as we usually do for +DataSources+. Of course the same approach can be used for any other
resource.

Let's create a simple +Stateless Session+ Bean that will deal with +com.mongodb.MongoClient+ connection class.

[source, java]
----
@Named
@Stateless
public class GreetingsSessionBean {

	@Resource(name = "mongoClient")
	private MongoClient mongoClient;

	DBCollection greetingsCollection;

	@PostConstruct
	private void initDB() {
		DB db = mongoClient.getDB("greetingsDB");
		greetingsCollection = db.getCollection("greetings");
		greetingsCollection.remove(new BasicDBObject());
	}

	public void createPerson(Greetings greetings) {
		BasicDBObject doc = greetings.toDBObject();
		greetingsCollection.insert(doc);
	}

	public List<Greetings> getGreetings() {
		List<Greetings> greetings = new ArrayList<>();
		
		DBCursor cur = greetingsCollection.find();
		
		for (DBObject dbo : cur.toArray()) {
			greetings.add(Greetings.fromDBObject(dbo));
		}

		return greetings;
	}

	public void removeGreetings() {
	    greetingsCollection.remove(new BasicDBObject());
	}
	
}
----

As you can see +@Resource+ annotation is used over +com.mongodb.MongoClient+ class, +Apache TomEE+ will be the
responsible of creating and injecting the resource.

Next step is configuring the +MongoDB+ connection. To do it we only need to create a +resources.xml+ file with
required parameters.

include::src/test/resources/resources.xml

Note that file is self-explained. +MongoClient+ has a constructor with single parameter where you set the host and in
this case this is the constructor that is resolved. You can think about +resources.xml+ file as +Spring+-like file
where constructors and getter/setters are resolved.

To be processed +resources.xml+ file should be added inside +WEB-INF+ directory.

And finally an +Arquillian+ test to check that resource is created correctly.

First step is creating a deployment file:

[source, java]
----
@Deployment
public static WebArchive deploy() {

    WebArchive webArchive = ShrinkWrap
            .create(WebArchive.class)
            .addClass(Greetings.class)
            .addClass(GreetingsSessionBean.class)
            .addAsWebInfResource("resources.xml")   // <1>
            .addAsLibraries(
                    Maven.resolver().loadPomFromFile("pom.xml").resolve("org.mongodb:mongo-java-driver")
                            .withTransitivity().asFile());

    return webArchive;

}
----
<1> resources.xml is added from classpath to WEB-INF

Thanks of +ShrinkWrap+, we can create as many +resources.xml+ files depending on the environments you must deploy the
application and add them selectively.

TIP: you can even create one +resources.xml+ file and override their values using system properties instead of having
several files. For example in this example we could override address property by using _-DmongoClient.address=ip_.

And finally we can call our +EJB+ as we usually do, and +Apache TomEE+ will take care for us of injecting
+MongoClient+ class.

A MongoDB server must be started at _localhost_ manually, but it is not required to create any _db_ nor _collection_
because they are automatically created by the driver.

[source, java]
----
@Test
public void shouldCreateGreetingsOnMongoDB() {

    greetingsSessionBean.removeGreetings();                             // <1>

    greetingsSessionBean.createPerson(new Greetings("Hello World!!"));  // <2>

    List<Greetings> greetings = greetingsSessionBean.getGreetings();    // <3>
    assertThat(greetings, hasItem(new Greetings("Hello World!!")));

}
----
<1> Previous Greetings are removed
<2> Create a new Greeting
<3> We assert that the Greeting is inserted
