= Injecting Properties

.Overview
****
After reading this example, you'll be able to:

* Inject values from properties file into simple POJO using _DeltaSpike_.
* Use _MongoDB java driver_ inside _Java EE_ application.
* Write tests using _Arquillian_.
****

One of the great improvement in _Java EE 5_ and beyond it is the introduction of _CDI_ (Context and Dependency Injection).
_CDI_ is used for injecting dependencies among a lot of other things like events, interceptors, ... and can be used in _POJOs_.

In some cases instead of injecting other objects (as a dependency injection), you want to inject a value from a properties file into a class that needs to be configured externally.

In current example you are going to explore how to configure a _MongoDB_ client, setting required parameters, that is _host_ and _port_, from a properties file called +mongodb.properties+.

The easiest way to do is using _DeltaSpike_ project.

_DeltaSpike_ consists on a number of portable _CDI_ extensions that provide useful features for Java application developers.
And in this case a core feature which is the configuration mechanism is going to be used.

The mechanism used by _DeltaSpike_ allows developers for dynamic configuration in case of JAR drop-in.

The first thing is add _DeltaSpike_ dependencies:

[source, xml]
----
<dependency xmlns="http://maven.apache.org/POM/4.0.0">
    <groupId>org.apache.deltaspike.core</groupId>
    <artifactId>deltaspike-core-api</artifactId>
    <version>${version.deltaspike}</version>
    <scope>compile</scope>
</dependency>

<dependency xmlns="http://maven.apache.org/POM/4.0.0">
    <groupId>org.apache.deltaspike.core</groupId>
    <artifactId>deltaspike-core-impl</artifactId>
    <version>${version.deltaspike}</version>
    <scope>runtime</scope>
</dependency>

----


Then you define our service to return the location of configuration file based on classpath. And this is done by implementing an SPI interface called +PropertyFileConfig+.

[source, java]
----
public class MongoDbConfigurationFile implements PropertyFileConfig {

    private static final long serialVersionUID = -7762380573887097591L;

    @Override
    public String getPropertyFileName() {
        return "mongodb.properties"; // <1>
    }

}
----
<1> This method should return the location and name of the properties file to be loaded. Classes implementing PropertyFileConfig will automagically get picked up by _DeltaSpike_ (via +ProcessAnnotatedType+) and will register all +mongodb.properties+ files on the classpath as +_DeltaSpike_ +ConfigSource+.

And that's all, now you can use +ConfigProperty+ annotation with +@Inject+ in your _POJOs_ and _CDI_ container will inject values configured within properties file.
In your case a file called _mongodb.properties_ located on root classpath.

For a more detailed explanation please check the _DeltaSpike_ project documentation at http://deltaspike.apache.org/configuration.html

Let's see an example of +mongodb.properties+ file.

.mongodb.properties
[source]
----
host = locahost
port = 27017
----

And then your _POJO_ may look like:

[source, java]
----
@ApplicationScoped
public class MongoDbFactory {

    MongoClient mongo;

    @Inject
    @ConfigProperty(name = "host") // <1>
    private String host;

    @Inject
    @ConfigProperty(name = "port")
    private Integer port; // <2>

    @PostConstruct // <3>
    public void init() {
        try {
            mongo = new MongoClient(host, port);
        } catch (UnknownHostException e) {
            throw new IllegalArgumentException(e);
        }
    }

    @Produces
    @RecipesCollection
    public DBCollection getRecipeCollection() { // <4>
        DB db = mongo.getDB("test");
        return db.getCollection("recipes");
    }
    
    public String getHost() {
        return host;
    }
    
    public Integer getPort() {
        return port;
    }

}
----
<1> Using +Inject+ and +ConfigProperty+ annotation from _DeltaSpike_ together to inject the configuration value.
<2> Native conversions are provided automatically.
<3> After the construction of this POJO, the +MongoClient+ instance is created with injected parameters.
<4> This method acts as a producer for _recipies MongoDB_ collections.

To test it an _Arquillian_ test is going to be used. For this case,  +JavaArchive+ must contain not only our code but also the _DeltaSpike_ library.

[source, java]
----
@RunWith(Arquillian.class)
public class MongoDbFactoryTest {

    private static final String MONGODB_PROPERTIES = "host = localhost" + System.getProperty("line.separator") + 
    		"port = 27017";
    
    @Deployment @OverProtocol("Servlet 3.0")
    public static JavaArchive createDeployment() {
        
        JavaArchive application = ShrinkWrap.create(JavaArchive.class) // <1>
                         .addPackage(MongoDbFactory.class.getPackage())
                         .addAsManifestResource(EmptyAsset.INSTANCE, "beans.xml")
                         .addAsResource(new StringAsset(MONGODB_PROPERTIES), "mongodb.properties"); // <2>
        
        application =  merge(application, Maven.resolver().loadPomFromFile("pom.xml")
                                        .resolve("org.apache.deltaspike.core:deltaspike-core-impl")
                                        .withTransitivity().as(JavaArchive.class)); // <3>
        
        return application;
        
    }
    
    private static JavaArchive merge(JavaArchive originalArchive, JavaArchive... mergedJavaArchives) {
        for (JavaArchive javaArchive : mergedJavaArchives) {
            originalArchive.merge(javaArchive);
        }
        
        return originalArchive;
        
    }
    
    @Inject
    MongoDbFactory mongoDbFactory;
    
    @Test
    public void should_load_mongodb__configuration_from_properties_file() {
       
       assertThat(mongoDbFactory.getHost(), is("localhost"));
       assertThat(mongoDbFactory.getPort(), is(27017));
        
    }
    
}
----
<1> A +JavaArchive+ is created with required classes bundled.
<2> +mongodb.properties+ is created from +String+ for testing purposes.
<3> _DeltaSpike_ dependencies are merged inside the +JavaArchive+.

'''

Injecting values from external file using _Delta Spike_ it is easy, but it has the drawback of having to add _Delta Spike_ as dependency. Probably this will be fixed in next version of _CDI_ spec.

If you are using +EJBs+ you can use +ejb-jar.xml+ for that purpose, but this is another history.

And you can even create your own +@Resource+ provider in _Apache TomEE_ as explained in https://github.com/tomitribe/community/tree/master/mongodb-example

WARNING: Creating your own resource provider will make your application not being portable across application servers.

